name: CI

on:
  pull_request:
    branches:
    - '*'
  push:
    branches:
    - main

defaults:
  run:
    shell: bash

jobs:
  all:
    name: All

    strategy:
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
    runs-on: ${{matrix.os}}

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust Toolchain Components
      uses: dtolnay/rust-toolchain@stable

    - uses: Swatinem/rust-cache@v2

    - name: Test
      run: cargo test --all
      working-directory: client/april


    - name: Clippy
      run: cargo clippy --all --all-targets -- -D warnings
      working-directory: client/april


    - name: Format
      run: cargo fmt --all --check
      working-directory: client/april
